
        uname: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Robot Framework tests
      - name: Run Robot Framework Tests
        run: |
          robot -d results automation/google.robot

      # Upload results as artifacts
      - name: Upload Robot Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/

